[workspace]
resolver = "2"

members = [
    "crates/league-mod",
    "crates/ltk_fantome",
    "crates/ltk_mod_core",
    "crates/ltk_modpkg",
    "crates/ltk_mod_project",
    "crates/ltk_pki",
    "crates/ltk-manager/src-tauri"
]

[workspace.dependencies]
camino = "1.1"
sysinfo = "0.32"
